### ISSUE TITLE
keys in viper are case-insensitive. Fix configuration to handle this

### ISSUE THREAD

**Issue by LandonTClipp** [LandonTClipp/makemock#1]
The keys in viper are case-insensitive. Meaning if you have a config like this:

```yaml
packages:
    DEFAULT:
        test1: test1_default
        test2: test2_default
    github.com/LandonTClipp/makemocks:
        test1: test1_landon
```

the names of the packages will be lower-cased in the final configuration struct.
